// Dialect translation for the Postgres driver.
//
// db.ts holds exactly one copy of every query, written in the SQLite flavour the
// project started with. Everything that differs between SQLite and Postgres is
// handled here so no query body needs per-dialect branching.

// Every timestamp/date column in this schema is TEXT, and SQLite renders
// CURRENT_TIMESTAMP into it as "YYYY-MM-DD HH:MM:SS". Postgres' CURRENT_TIMESTAMP
// is a timestamptz that will not implicitly cast into a text column, and would
// render with fractional seconds and an offset even if it did -- which would break
// the lexical string comparisons this code does on expires_at/completed_at.
const PG_NOW = "to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')";

// Applied to both DDL and DML: CURRENT_TIMESTAMP appears in ~30 INSERT/UPDATE
// statements as well as in column defaults.
function translateForPostgres(sql: string): string {
  return sql
    .replace(
      /INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi,
      "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    .replace(/\bCURRENT_TIMESTAMP\b/gi, PG_NOW);
}

// Rewrite better-sqlite3's positional "?" markers into Postgres' $1..$n.
//
// This runs on the fully assembled statement, which is what makes the dynamic-SQL
// sites safe: db.ts builds some WHERE clauses and IN lists from a variable number
// of fragments, so the correct index for a given "?" is only knowable once the
// string is complete. Quoted literals, quoted identifiers, dollar-quoted strings
// and comments are skipped so a "?" inside them is left alone.
function toPositionalParams(sql: string): string {
  let out = "";
  let index = 0;
  let i = 0;

  while (i < sql.length) {
    const char = sql[i];

    if (char === "'" || char === '"') {
      const quote = char;
      out += char;
      i++;
      while (i < sql.length) {
        out += sql[i];
        if (sql[i] === quote) {
          // Doubled quote is an escaped quote, not the end of the literal.
          if (sql[i + 1] === quote) {
            out += sql[i + 1];
            i += 2;
            continue;
          }
          i++;
          break;
        }
        i++;
      }
      continue;
    }

    if (char === "-" && sql[i + 1] === "-") {
      while (i < sql.length && sql[i] !== "\n") {
        out += sql[i];
        i++;
      }
      continue;
    }

    if (char === "/" && sql[i + 1] === "*") {
      while (i < sql.length && !(sql[i] === "*" && sql[i + 1] === "/")) {
        out += sql[i];
        i++;
      }
      out += sql.slice(i, i + 2);
      i += 2;
      continue;
    }

    if (char === "$" && sql[i + 1] === "$") {
      out += "$$";
      i += 2;
      while (i < sql.length && !(sql[i] === "$" && sql[i + 1] === "$")) {
        out += sql[i];
        i++;
      }
      out += sql.slice(i, i + 2);
      i += 2;
      continue;
    }

    if (char === "?") {
      index++;
      out += `$${index}`;
      i++;
      continue;
    }

    out += char;
    i++;
  }

  return out;
}

module.exports = { translateForPostgres, toPositionalParams, PG_NOW };
